# Generated by Django 4.1.4 on 2022-12-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='collection_id',
            new_name='collection',
        ),
    ]
